version: '3'

services:

  app1:
    build: ./server1
    container_name: spring-app1

  app2:
    build: ./server2
    container_name: spring-app2

  nginx:
    image: nginx:latest
    container_name: nginx-lb

    ports:
      - "8080:80"

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

    depends_on:
      - app1
      - app2