name: Deploy to OCI Instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Deploy to OCI Server
        uses: appleboy/ssh-action@master

        with:
          host: ${{ secrets.OCI_HOST }}
          username: ${{ secrets.OCI_USERNAME }}
          key: ${{ secrets.OCI_SSH_KEY }}

          script: |
            cd ~/load-balancer/load-balancer

            git pull origin main

            cd server1
            mvn clean package -DskipTests

            cd ../server2
            mvn clean package -DskipTests

            cd ..

            docker-compose down
            docker-compose up --build -d
